<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container63Slkxn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container63Slkxn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container63Slkxn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container63Slkxn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container63Slkxn\App_KernelDevDebugContainer([
    'container.build_hash' => '63Slkxn',
    'container.build_id' => '8b7d1912',
    'container.build_time' => 1715287066,
], __DIR__.\DIRECTORY_SEPARATOR.'Container63Slkxn');
