<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrVmNAv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrVmNAv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRrVmNAv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRrVmNAv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRrVmNAv\App_KernelDevDebugContainer([
    'container.build_hash' => 'RrVmNAv',
    'container.build_id' => '467f5638',
    'container.build_time' => 1715295255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrVmNAv');
