<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2SRDau1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2SRDau1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2SRDau1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2SRDau1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2SRDau1\App_KernelDevDebugContainer([
    'container.build_hash' => '2SRDau1',
    'container.build_id' => 'a4ae1f1d',
    'container.build_time' => 1714500044,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2SRDau1');
